---
        deployment:
                tasks:
                        - export DEPLOYPATH=/home3/sparked8/public_html/test
                        - /bin/cp -R public $DEPLOYPATH
                        - /bin/cp -R resources $DEPLOYPATH
                        